run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Suggest code simplifications
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - misspell      # Find commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - typecheck     # Type-check Go code
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - goconst       # Find repeated strings that could be replaced by a constant
    - gocyclo       # Compute cyclomatic complexities of functions
    - dupl          # Check for code duplication
    - gosec         # Inspect source code for security problems

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    # Exclude known false positives
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - revive
      text: "exported: exported"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
